@startuml
!theme plain
hide footbox
autonumber

actor "APP" as APP
participant "Middleware" as MW
participant "Banco de Comercio" as BDC

title GET /bdc/sub-account/{origin_id}?token=<JWT_APP>
APP -> MW: GET /bdc/sub-account/{origin_id}
MW -> MW: Validar JWT APP
MW -> BDC: GET /sub-account/{origin_id}
BDC --> MW: detalle subcuenta / error
MW --> APP: 200 / 4xx / 5xx

@enduml
