@startuml
!theme plain
hide footbox
autonumber

actor "APP" as APP
participant "Middleware" as MW
participant "Banco de Comercio" as BDC

title POST /bdc/movements/{cbu_cvu_alias}?token=<JWT_APP>
APP -> MW: POST /bdc/movements/{id}
MW -> MW: Validar JWT APP
MW -> MW: Calcular X-SIGNATURE
MW -> BDC: POST /movements/{id}
BDC --> MW: movimientos / error
MW --> APP: 200 / 4xx / 5xx

@enduml
